BOOTMAGIC_ENABLE = yes
TRI_LAYER_ENABLE = yes
CAPS_WORD_ENABLE = yes
REPEAT_KEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
SEND_STRING_ENABLE = no

LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no

COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
VIA_ENABLE = no

OLED_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
